export const cataractContent = {
  whatIsCataract: {
    eyebrow: "Understanding Cataracts",
    title: "What Is a Cataract?",
    paragraphs: [
      "A cataract occurs when the natural lens of the eye becomes cloudy, causing blurred vision, glare, difficulty reading, poor night vision, and reduced clarity. Cataracts are commonly age-related, but they can also develop due to other eye or health conditions.",
      "At Namokar Eye & Oculoplasty Centre, cataract treatment is planned after a detailed eye evaluation, lens power calculation, and discussion of the most suitable intraocular lens option for the patient.",
    ],
    cta: {
      label: "Learn more about Namokar Eye & Oculoplasty Centre",
      href: "/about",
    },
    image: {
      src: "/assets/cataract/what_is_cataract.png",
      alt: "Close-up medical view of an eye with cataract",
    },
  },
  evaluationSigns: {
    title: "Signs That May Require a Cataract Evaluation",
    items: [
      { id: 1, label: "Cloudy or blurred vision" },
      { id: 2, label: "Difficulty seeing at night" },
      { id: 3, label: "Glare from headlights or bright lights" },
      { id: 4, label: "Colours appearing faded" },
      { id: 5, label: "Frequent spectacle-power changes" },
      { id: 6, label: "Double vision in one eye" },
    ],
  },
  lensOptions: {
    eyebrow: "LENS OPTIONS",
    titleLine1: "Our Advanced",
    titleLine2: "Cataract Care",
    subtitle: "Types of Intraocular Lenses (IOLs) - Choose the best option for your lifestyle",
    items: [
      {
        id: "monofocal",
        title: "Standard Monofocal",
        category: "SINGLE FOCUS LENS",
        description: "Provides clear vision at one distance (usually far). Reading glasses may still be needed for close work.",
        points: [
          "Clear distance vision",
          "Covered by insurance",
          "Proven reliability",
        ],
        image: {
          src: "/assets/cataract/lens_monofocal.png",
          alt: "Standard Monofocal Eye Exam",
        },
        icon: "Eye",
        featured: false,
      },
      {
        id: "multifocal",
        title: "Premium Multifocal",
        category: "MULTIPLE FOCUS LENS",
        description: "Enables clear vision at multiple distances —near, intermediate, and far—reducing dependence on glasses.",
        points: [
          "Multiple focal points",
          "Reduced glasses dependency",
          "Enhanced lifestyle",
        ],
        image: {
          src: "/assets/cataract/lens_multifocal.png",
          alt: "Premium Multifocal Advanced Testing",
        },
        icon: "Sparkles",
        featured: true,
      },
      {
        id: "toric",
        title: "Toric Lens",
        category: "ASTIGMATISM CORRECTION",
        description: "Specially designed to correct astigmatism while providing clear distance vision in one procedure.",
        points: [
          "Corrects astigmatism",
          "Sharper clarity",
          "Single procedure",
        ],
        image: {
          src: "/assets/cataract/lens_toric.png",
          alt: "Toric Lens Doctor Consultation",
        },
        icon: "Target",
        featured: false,
      },
    ],
  },
  stitchlessSurgery: {
    eyebrow: "Our Advanced Treatment",
    titleLine1: "Stitchless",
    titleLine2: "Cataract Surgery",
    subtitle: "A safer, faster and more comfortable way to restore clear vision",
    whatIs: {
      title: "What is Stitchless Cataract Surgery?",
      description:
        "Stitchless cataract surgery is performed using the phacoemulsification technique. In this method, the cloudy lens is removed through a tiny self-sealing incision and replaced with an artificial intraocular lens.",
    },
    benefitsTitle: "Key Benefits",
    benefits: [
      { id: 1, label: "Tiny micro-incision approach", icon: "Minimize2" },
      { id: 2, label: "No stitches required", icon: "Scissors" },
      { id: 3, label: "No bandage in most cases", icon: "Bandage" },
      { id: 4, label: "Quick procedure", icon: "Timer" },
      { id: 5, label: "Faster recovery", icon: "CalendarCheck" },
      { id: 6, label: "Premium IOL options available", icon: "Eye" },
      { id: 7, label: "Planned with detailed pre-operative evaluation", icon: "ClipboardList" },
    ],
    image: {
      src: "/assets/cataract/stitchless_surgery_tech.png",
      alt: "Stitchless Cataract Surgery IOL Technology",
    },
    ctaBanner: {
      quote: "Clearer vision. Brighter tomorrow.",
      btnLabel: "Book Your Cataract Consultation",
      btnHref: "/appointment",
    },
  },
  whyChooseNamokar: {
    eyebrow: "WHY CHOOSE US",
    titleLine1: "Why Choose",
    titleLine2: "Namokar?",
    reasons: [
      {
        id: 1,
        title: "Led by Dr. Poonam Jain",
        subtitle: "Medical Director & Senior Ophthalmologist",
        icon: "UserCheck",
        colorScheme: "blue",
      },
      {
        id: 2,
        title: "30+ Years of Eye Care Experience",
        subtitle: "Decades of expertise. Thousands of happy patients.",
        icon: "Award",
        colorScheme: "orange",
      },
      {
        id: 3,
        title: "NABH-accredited Eye Centre",
        subtitle: "Trusted quality and safety standards in North Delhi.",
        icon: "Building2",
        colorScheme: "blue",
      },
      {
        id: 4,
        title: "Advanced Cataract and Oculoplasty",
        subtitle: "Comprehensive care for complex eye conditions under one roof.",
        icon: "Eye",
        colorScheme: "orange",
      },
      {
        id: 5,
        title: "Patient-centric Treatment Planning",
        subtitle: "Personalized care tailored to your unique needs.",
        icon: "Users",
        colorScheme: "blue",
      },
      {
        id: 6,
        title: "Cashless and EMI Support",
        subtitle: "Hassle-free treatment with flexible payment options.",
        icon: "IndianRupee",
        colorScheme: "orange",
      },
    ],
    image: {
      src: "/assets/cataract/why_choose_namokar_doctor.png",
      alt: "Dr. Poonam Jain consulting a patient at Namokar Eye Centre",
    },
    highlights: [
      {
        id: 1,
        titleLine1: "Experienced",
        titleLine2: "Specialist Team",
        subtitle: "Compassionate care at every step",
        icon: "Users",
        highlightColor: "blue",
      },
      {
        id: 2,
        titleLine1: "Advanced",
        titleLine2: "Technology",
        subtitle: "State-of-the-art infrastructure",
        icon: "ShieldCheck",
        highlightColor: "orange",
      },
      {
        id: 3,
        titleLine1: "Trusted by",
        titleLine2: "Thousands",
        subtitle: "Proven results. Stronger trust.",
        icon: "HeartHandshake",
        highlightColor: "blue",
      },
      {
        id: 4,
        titleLine1: "Committed to",
        titleLine2: "Better Vision",
        subtitle: "Your vision. Our mission.",
        icon: "Heart",
        highlightColor: "orange",
      },
    ],
  },
};
